# Generated by Django 4.2.4 on 2023-08-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='bame',
            new_name='name',
        ),
    ]
